### ISSUE TITLE
Agent disconnect after each notify FIN

### ISSUE THREAD

**Issue by cortex93** [haproxytech/haproxy-spoa-dotnet#2]
Hi,

What is the purpose of closing the connection after each FIN frame ?

I made some quick benchmarks and withtout closing the connection, I can process around 8 000 spoe message per second with 100% CPU usage, while with disconnecting ,  cpu usage is around 20% in average with some spikes (I guess due to the ThreadPool contention) and I reach only 1 200 frame/s.

**Comment by NickMRamirez** [comment]
Great question. I did it that way because:

1. I want to close the connection a soon as possible because I was only going to send one response and then nothing else. If I don't close it, the connection idles there until the configured timeout, which meant a delay before HAProxy would process the response on its end (if I recall correctly).

2. I'm passing the stream object into `HandleStream` and didn't see a clear way to manage closing the connection from outside that function.

It's entirely possible that there's a way to do what you suggest. The program just needs a way to control closing the connection as soon as possible (when the work is done), and not leaving it open until a timeout. Maybe a `Close` function that checks whether some condition is true after every Ack message is sent? i.e. when is the agent finished with the connection and ready to send a disconnect? I think it would have to be an `Func` delegate that is passed as a parameter to `HandleStream`, and that returns a bool, so that the condition for when to disconnect could be checked? Perhaps with a default function implementation that just returns true.

**Comment by cortex93** [comment]
1. Looking at diagram sequence in the SPOE spec, only the ``HAPROXY-HELLO[healthcheck:true]`` needs to be close right after sending the ``AGENT-HELLO`` ack.
Keeping the connection open for other frame, allows HAProxy to reuse this connection, for many differents sessions.

2. Passing a CancelationToken to the ``HandleStream`` will allow to control the end of the HandleStream from the outside. Moving all blocking calls to async, will allow to cancel the stream.Read for e.g. and exit the while(true) loop smoothly. With linked token sources (a token from the HandleStream argument and one owned by FrameProcessor), handling ``Haproxy Disconnect`` should be as easy a cancelling the token source owned by FrameProcessor.

**Comment by cortex93** [comment]
After some more tests regarding idling connection. Behavior depends on haproxy configuration.
If the spoe `timeout idle` is lower than the backend `timeout server`, when the spoe timeout occured, haproxy will send a `HaproxyDisconnect` with status code 2 (a timeout occured). The spoa may reply with `AgentDisconnect` and close the connection. This should be considered a norminal use case and the spec tells to configure that way.
The spoa may want to close the connection before haproxy and to do so, send `AgentDisconnect` and close the connection first.

If otherwise, when the backend timeout occured, haproxy send a `HaproxyDisconnect` with status code 1 (I/O error) and close the connection.


Regarding other status code, I don't kwnow if Haproxy waits for an `AgentDisconnect` or close the connection immediately.

**Comment by cortex93** [comment]
Haproxy has some concurrent call issues that I explain here https://discourse.haproxy.org/t/some-spoe-streams-fails-intermittently-with-st-258/5276/2
I tried to implement pipelining has the maximum number of concurrent notify frames per connection is configurable but it doesn't help either.
I need to do some testing with others spoe implementations to see how it behaves.

**Comment by NickMRamirez** [comment]
I began an implementation for keeping the connection open so that HAProxy can send multiple streams over it, but ran into something I think is an issue. Opened a bug report with HAProxy here: https://github.com/haproxy/haproxy/issues/690

**Comment by cortex93** [comment]
As far as I remember, HAProxy will open 20 connections before reusing them with maxconn set to 0 (default). To force connection reuse for integration testing, I set maxconn to 1.

Having done some test with the C sample implementation, and I observe the same concurrent issue when two notify frames are to be sent at the exact same time. One of them is deadlock and will timeout even if the other one did completed.
